# Generated by Django 5.2 on 2025-05-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingcenter',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
